// ---------------------------------------------------------------------------
// Mapa de iconos: traduce las claves usadas en src/data/*.js (kebab-case) a
// los componentes de Lucide. Así los archivos de datos no dependen de React.
// ---------------------------------------------------------------------------
import {
  HelpCircle,
  AlertTriangle,
  Package,
  Boxes,
  PenTool,
  ShieldCheck,
  Clock,
  Sparkles,
  Layers,
  Scissors,
  Stamp,
  Flame,
  Shirt,
  MessageCircle,
  BadgeCheck,
  TrendingUp,
  Users,
  Rocket,
  MessageSquareText,
  ClipboardCheck,
  Truck,
  Briefcase,
  Crown,
  Medal,
  ShoppingBag,
  Coffee,
  CupSoda,
  Utensils,
  Gift,
  Building2,
  Store,
  School,
  PartyPopper,
  Megaphone,
} from "lucide-react";

export const iconMap = {
  "help-circle": HelpCircle,
  "alert-triangle": AlertTriangle,
  package: Package,
  boxes: Boxes,
  "pen-tool": PenTool,
  "shield-check": ShieldCheck,
  clock: Clock,
  sparkles: Sparkles,
  layers: Layers,
  scissors: Scissors,
  stamp: Stamp,
  flame: Flame,
  shirt: Shirt,
  "message-circle": MessageCircle,
  "badge-check": BadgeCheck,
  "trending-up": TrendingUp,
  users: Users,
  rocket: Rocket,
  "message-square-text": MessageSquareText,
  "clipboard-check": ClipboardCheck,
  truck: Truck,
  briefcase: Briefcase,
  crown: Crown,
  medal: Medal,
  "shopping-bag": ShoppingBag,
  coffee: Coffee,
  "cup-soda": CupSoda,
  utensils: Utensils,
  gift: Gift,
  "building-2": Building2,
  store: Store,
  school: School,
  "party-popper": PartyPopper,
  megaphone: Megaphone,
};

export function Icon({ name, ...props }) {
  const Cmp = iconMap[name] || Sparkles;
  return <Cmp {...props} />;
}
